/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const GasMixture = IDL.Record({
  'mixType' : IDL.Text,
  'heliumPercentage' : IDL.Nat,
  'name' : IDL.Text,
  'tankSize' : IDL.Nat,
  'oxygenPercentage' : IDL.Nat,
  'timestamp' : Time,
  'workingPressure' : IDL.Nat,
  'nitrogenPercentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'clearAllCalculations' : IDL.Func([], [], []),
  'deleteCalculation' : IDL.Func([IDL.Nat], [], []),
  'getAllCalculations' : IDL.Func([], [IDL.Vec(GasMixture)], ['query']),
  'saveCalculation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const GasMixture = IDL.Record({
    'mixType' : IDL.Text,
    'heliumPercentage' : IDL.Nat,
    'name' : IDL.Text,
    'tankSize' : IDL.Nat,
    'oxygenPercentage' : IDL.Nat,
    'timestamp' : Time,
    'workingPressure' : IDL.Nat,
    'nitrogenPercentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'clearAllCalculations' : IDL.Func([], [], []),
    'deleteCalculation' : IDL.Func([IDL.Nat], [], []),
    'getAllCalculations' : IDL.Func([], [IDL.Vec(GasMixture)], ['query']),
    'saveCalculation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };