/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GasMixture {
  'mixType' : string,
  'heliumPercentage' : bigint,
  'name' : string,
  'tankSize' : bigint,
  'oxygenPercentage' : bigint,
  'timestamp' : Time,
  'workingPressure' : bigint,
  'nitrogenPercentage' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'clearAllCalculations' : ActorMethod<[], undefined>,
  'deleteCalculation' : ActorMethod<[bigint], undefined>,
  'getAllCalculations' : ActorMethod<[], Array<GasMixture>>,
  'saveCalculation' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];